### PR TITLE
Update Gi-pango and Related Dependencies

### LINKED ISSUE #45: Self-compile not working on Debian Buster
Since my glibc version is not high enough on Debian, I had to self-compile the project. I installed all the dependencies, but when I ran `make`, it installed most of the stuff and then throws an error. Here's a screenshot: 

image

What has me a bit worried is that it says `linux-notification-center-1.6.0`. Is it supposed to do that? I definitely downloaded version 1.7.2.

### LINKED ISSUE #85: Update Stack.yaml and Cabal Files
The lastest stack and cabal files are from 6 months ago and were generated from the 1.6.0 build.

The gi-pango 1.0.22 from that build has a bug where it parses harfbuzz incorrectly as reported here
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=968729
and got fixed in gi-pango 1.0.23

The gi-pango bug is also reported here:
https://aur.archlinux.org/packages/deadd-notification-center/

My best guess is that current 1.7.2 was built on a different stack LTS GHC than the latest stack.yaml and .cabal files posted in the repo.

```
gi-pango                 > [85 of 94] Compiling GI.Pango.Objects.Font
gi-pango                 >
gi-pango                 > /tmp/stack-69059c6a2ea7a9dc/gi-pango-1.0.22/GI/Pango/Objects/Font.hs:669:9: error:
gi-pango                 >     parse error on input ‘HarfBuzz.FeatureT.feature_t’
gi-pango                 >     |
gi-pango                 > 669 |     Ptr HarfBuzz.FeatureT.feature_t ->      -- features : TCArray False (-1) 2 (TInterface (Name {namespace = "HarfBuzz", name = "feature_t"}))
gi-pango                 >     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi-pango                 >

```

### PR DESCRIPTION
**Pull request by mitchell-gil96**
Could not compile with gi-pango-1.0.22 as specified in the latest stack.yaml file.
This is due to a bug in that specific version where it could not parse harfbuzz.
Further information on the error as well as the merge to fix it in here:
https://github.com/haskell-gi/haskell-gi/issues/298

The fix has been implemented in gi-pango-1.0.23. That package also requires gi-harfbuzz-0.0.3 as a new dependency. 
The rest of the dependencies have been updated in accordance with this sheet:
https://hackage.haskell.org/package/gi-pango

I was able to build successfully using this configuration.

Definitely closes #85 , could potentially close #45 as well since it was a gtk3 error and gi-gtk is bumped to 3.0.36. There is a thread mentioning it was fixed in gtk3-3.24.7

https://bugs.archlinux.org/task/61486

### CODE REVIEW

**Comment by phuhl** [comment]
Nice, thanks for the PR :)
